# Visualize schema at: https://editor.swagger.io/
openapi: 3.0.4
info:
  title: NetActuate Cloud API
  description: This API is for managing your resources at NetActuate
  version: 0.1.0
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: key
  schemas:
    Server:
      required:
        - mbpkgid
      type: object
      properties:
        mbpkgid:
          type: integer
          format: int64
          example: 10

security:
  - ApiKeyAuth: []
servers:
  - url: 'https://vapi2.netactuate.com/api/'
    description: Main server

paths:
  /cloud/servers:
    get:
      summary: List Cloud Servers
      description: This route returns a list of your cloud servers
      responses:
        '200':
          description: Required Auth Token
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Server"
  /cloud/server:
    get:
      summary: Cloud Server Details
      description: This route returns the details for a given cloud server mbpkgid
      parameters:
        - in: query
          name: mbpkgid
          schema:
            type: integer
            format: int64
          description: The package ID (mbpkgid) for the desired server
      responses:
        '200':
          description: Required Auth Token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
        '400':
          description: Invalid ID provided
        '404':
          description: Banner not found
        '500':
          description: sumting wong


# const mbpkgid: 'Primary key for the virtual server. Used with other cloud endpoints.'
# const state: 'UP or DOWN. Indicates power state of the virtual machine.'
# const status: 'RUNNING, STOPPED, or TERMINATED. Indicates status rather than state.'
# const fqdn: 'Hostname for the server. This can be updated via settings on portal or API.'
# const rescue_mode: '0 or 1. Indicates if the server is in rescue mode'
# const uptime: 'Seconds the instance has been alive for.'
# const locked: '0 or 1. Server can be locked by NetActuate staff.'
# const installed: '0 or 1. Indicates if a server has an OS installed.'
# const autorescue: '0 or 1. Starts server if it is detected offline. Can be changed via settings.'
# const os_id: 'ID for the operating system the server is running.'
# const os: 'Plain name for the operating system.'
# const package: 'The current plan for the server. This currently can not be changed.'
# const ip: 'The primary IPv4 assigned to the server.'
# const ipv6: 'The primary IPv6 assigned to the server.'
# const city: 'The city in which the datacenter resides in.'
# const location_id: 'ID of the deployed cloud location for the server.'
# const boot: 'Current boot mode configured. Can be changed via settings.'
# 
